version: '3.8'

services:
  backend:
    build: ./backend
    container_name: hermes-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/example.env
    volumes:
      - ./backend:/app
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_USER: hermes
      POSTGRES_PASSWORD: hermes
      POSTGRES_DB: hermes
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data: