services:
  backend:
    build: ./backend
    container_name: hermes-backend
    ports:
      - "8001:8000"
    env_file:
      - ./backend/example.env
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: hermes-frontend
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app

  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_USER: hermes
      POSTGRES_PASSWORD: hermes
      POSTGRES_DB: hermes
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: